### ISSUE TITLE
Sorting Option does not work

### ISSUE THREAD

**Issue by thygrrr** [SillyGoobersCreations/lumetra#14]
Toggling between Ascending / Descending sort order does nothing, reproduction visible on https://meet.godotengine.org/events/9d34768c-3e28-480f-83be-b8d3242cd127/attendees

https://github.com/user-attachments/assets/a413811f-2b4f-403d-9bb5-85e1858418aa

**Comment by LauraWebdev** [comment]
This is now fixed and will be deployed to the GodotCon instance soon.
