### ISSUE TITLE
Increase default result limit to 500

### ISSUE THREAD

**Issue by thygrrr** [SillyGoobersCreations/lumetra#15]
Since Lumetra does not paginate, 20 results are not enough.

It's impossible to find interesting people beyond the first 20 that any of the lists shows the user.

I recommend setting it to 500 until pagination is implemented, as this is the approximate upper bound of users at GodotCon 2024 Berlin that would benefit from this.

Even at a "maxed" out 500 users, this would not be too slow as the amount of requests and time users spend in a session is relatively low.

https://github.com/user-attachments/assets/ab3408b7-e4d7-435c-9b7b-9431e3e98b95

**Comment by LauraWebdev** [comment]
I've actually seen this while in a cafe with some Godot people, ultimately, we do want a pagination here. I'll see if I can whip this up before GodotCon

**Comment by LauraWebdev** [comment]
This is now fixed and will be deployed to the GodotCon instance soon.
