### ISSUE TITLE
About Me input is very small, does not respect whitespace on output

### ISSUE THREAD

**Issue by thygrrr** [SillyGoobersCreations/lumetra#16]
![image](https://github.com/user-attachments/assets/561aadc1-44f4-4752-a73a-cbd21e0000a1)

The About Me input field is very small, which reduces usability and discourages verbosity. (it's possible to expand it, but it's very small to begin with).

![image](https://github.com/user-attachments/assets/362e144c-6298-4952-96ac-1aa34546dc26)

It also does not respect whitespace or paragraphs when displayed

### Input (expanded)
![image](https://github.com/user-attachments/assets/c8c1d332-91b3-4b5e-a0b2-a709aaa86065)

### Display
![image](https://github.com/user-attachments/assets/71458f75-6332-4b14-94b0-71e70725d131)

**Comment by LauraWebdev** [comment]
This is now fixed and will be deployed to the GodotCon instance soon.
