### ISSUE TITLE
Multiple Notifications with same destination still need to be individually clicked

### ISSUE THREAD

**Issue by thygrrr** [SillyGoobersCreations/lumetra#17]
Clicking on a notification brings the user to the chat, but they still have to click every single notification to acknowledge them.

https://github.com/user-attachments/assets/75bee9e5-fde1-4a6a-a801-dd757d23ac34

**Comment by LauraWebdev** [comment]
Maybe a simple "Clear all" button would be best here?

**Comment by LauraWebdev** [comment]
This has been fixed in #23
