### ISSUE TITLE
chmod 777 -R widely considered harmful

### ISSUE THREAD

**Issue by thygrrr** [SillyGoobersCreations/lumetra#18]
file Readme.md suggests:

> You might need to run chmod 777 -R . after cloning this repo to run the system properly.

This is a dangerous practice and is not recommended. At the very least, after "cloning this repo" (running git clone), the user is likely to be in their home directory; this can expose their .ssh keys etc. to other users and processes on the system.

Even when the user changes directory to the cloned repo, it's also widely discouraged for any other paths and directory trees.

(one) Source:
https://devineer.medium.com/linux-permissions-unraveled-how-to-avoid-chmod-777-and-keep-the-chaos-at-bay-8874e069a121#:~:text=By%20executing%20chmod%20777%20%2C%20you,or%20process%20on%20the%20system.

A blanked 777 permission should especially not be set on directories that a web server serves content from and/or that contains portions of its own code base.

**Comment by LauraWebdev** [comment]
Agreed, and we do not set the permissions to 777 on prod. For some reason though, creating files within the sail container in dev made them uneditable on the host, even when setting the appropriate uid and gid in docker.

This is basically a big hammer for a small issue we had to fix to work on this in local dev for now.

**Comment by LauraWebdev** [comment]
This has been fixed in #23
