### ISSUE TITLE
No information on TOS or data protection available

### ISSUE THREAD

**Issue by heckert-gamedev** [SillyGoobersCreations/lumetra#21]
Where is it running, where and how do you store my user data?
Forwarding personal information to 3rd party side (like Ad providers) should certainly be less of an issue as with most other run-off-the-mill web services these days, but it still needs to tell what data is stored where and processed in which way...

**Comment by LauraWebdev** [comment]
This has been fixed in #23, in general, Godot's privacy policy was applied and users were informed through email for GodotCon
