### ISSUE TITLE
Uploading a new profile picture restores the previous one

### ISSUE THREAD

**Issue by outfrost** [SillyGoobersCreations/lumetra#22]
I have a profile picture on my event profile. I wanted to change it. If I upload a new pfp, or remove existing and then upload new one, Lumetra reuses the previous, existing (and supposedly deleted) one. So, I think users are stuck with either no pfp, or the first one they uploaded.

Browser: Firefox for Android 131.0.2

**Comment by LauraWebdev** [comment]
Seems to be the caching of Cloudflare, since changing the avatar removes the old and uploads the new at the same location. We'll implement cache busting measures after GodotCon

**Comment by LauraWebdev** [comment]
This has been fixed in #23
